### ISSUE TITLE
EPGStationのBasic認証対応について

### ISSUE THREAD

**Issue by unicode45** [l3tnun/plugin.video.epgstation#1]
EPGStationにBasic認証が実装され、早速使わせていただいていますが、
KODI PluginのURLに
http://user:pass@192.168.0.2:8888
の形式で指定しても認証は通らないようです。

**Comment by l3tnun** [comment]
対応しました。
ご確認ください。

**Comment by unicode45** [comment]
ご対応ありがとうございます！
http://user:pass@url:port
で無事ログインできました。
