### ISSUE TITLE
録画ファイルのリアルタイムエンコード方法指定

### ISSUE THREAD

**Issue by unicode45** [l3tnun/plugin.video.epgstation#2]
ライブ視聴の場合はm3u8ファイルの最後に?mode=2などを追加してエンコード方法を指定することができますが、addonではこのようにリアルタイムエンコード方法は選択できませんでしょうか？

**Comment by l3tnun** [comment]
EPGStation では録画をエンコードしながら視聴する場合、HLS 形式で対応するようになっています。
HLS 形式での配信は、エンコードが完了していない範囲にはシークできないので日常的にエンコードしながら視聴する事は想定していません。
外出時に回線が細くて再生できない等の場合に、急場凌ぎとして HLS 配信で見るというのを想定しています。
そして一番の問題は kodi が HLS に対応していないことです。
そのため plugin.video.epgstation ではエンコードしながら視聴ができません。

解決するには、EPGStation に Chinachu のような live 配信機能があればいいのですが、Chinachu のコードを見る限り実装コストが高いので今すぐに対応というのは無理です。
PC の webUI 内で ts を変換しながら視聴する際にとても便利なのでいつかは実装したいですが、他にやりたい事があるので優先度は低めです。（プルリクがあれば大歓迎ですが。）

まとめると
* kodi が HLS に非対応で現状対応不可能
* Chinachu のように変換しながら見ることはできなくはないが、実装コスト的に辛い

そのうち対応するかもしれませんが、それが何時になるかは未定です。

**Comment by unicode45** [comment]
Kodi自体がHLSに対応していなかったんですね。親切なご説明、ありがとうございます。

**Comment by l3tnun** [comment]
EPGStation の streaming ブランチにて録画をストリーミング視聴する api を追加して kodi にて再生できるか実験しましたが、シークができなく実用性が乏しい結果になりました。
Chinachu + Harekaze/pvr.chinachu + Kodi でも試してみましたが結果は同じで、デスクトップ版 VLC ではシークできたので可能だと思っていましたがそうではなかったようです。

あと、Kodi が HLS 配信に対応していないと上で書いていますが、それは間違いでした。
私が Kodi への HLS のプレリストの指定方法を間違えていただけでした。申し訳ない。
ただ、エンコード途中の HLS 配信を kodi で最初から見たり巻き戻したりはできないようなので、リアルタイムエンコードの機能としては使用できないです。

私の知識ではシークができない原因が分からないので plugin.video.epgstation でのリアルタイムエンコードの実装は見送ろうと思います。
