### ISSUE TITLE
[質問] 主音声を指定して再生する方法

### ISSUE THREAD

**Issue by unicode45** [l3tnun/plugin.video.epgstation#3]
お世話になります。

plugin.video.epgstationと併用してリアルタイム視聴ではIPTV Simple Clientを使っていますが、
無変換の再生で多重音声の主音声を指定するために、m3u8?mode=2にし、
config.jsonのmpegTsStreamingの「無変換」に

`"cmd": "%FFMPEG% -re -dual_mono_mode main -i pipe:0 -c:a aac -ar 48000 -ab 192k -ac 2 -c:v copy -f mpegts pipe:1"`

のように音声だけを処理して楽しませていただいております。

このようにplugin.video.epgstationの場合も主音声だけを選択して再生でする設定や指定方法はありませんでしょうか？

**Comment by l3tnun** [comment]
kodi側での対応が必要なので無理ですね。

**Comment by unicode45** [comment]
ご説明ありがとうございます。
