### ISSUE TITLE
kodiからの録画ファイル削除エラー

### ISSUE THREAD

**Issue by maru-x** [l3tnun/plugin.video.epgstation#4]
kodiから録画ファイルを削除しようとするとエラーとなり削除できません。
ログを調べたところdelete.pyの21行目にて引数エラーが発生していました。

if dialog.yesno(xbmc.getLocalizedString(122).encode('utf_8'), xbmc.getLocalizedString(433).encode('utf_8') % fileName, yeslabel=xbmc.getLocalizedString(117)):

上記の
xbmc.getLocalizedString(433).encode('utf_8') % fileName
のところですが、strings.poの#433を調べたところ%sではなく{0:s}となっており、delete.pyの21行目を

if dialog.yesno(xbmc.getLocalizedString(122).encode('utf_8'), xbmc.getLocalizedString(433).encode('utf_8').format(fileName), yeslabel=xbmc.getLocalizedString(117)):

と書き換えたところ、正常に削除することができました。

ご報告まで。

**Comment by l3tnun** [comment]
報告ありがとうございます。

どうやらkodi v18からはその様になっているようですね。
手が空き次第修正します

**Comment by l3tnun** [comment]
最新の master にて修正完了しました。
試してみてください。

**Comment by maru-x** [comment]
問題なく動作することを確認しました。
元のxbmc.getLocalizedString(433)のメッセージは日本語がおかしかったので今回修正された内容の方がシンプルで良いですね。kodiのバージョンも選ばないですし。
対応ありがとうございました。
