### ISSUE TITLE
subDirectory運用時に録画ファイルが見えない

### ISSUE THREAD

**Issue by masahiko-imai** [l3tnun/plugin.video.epgstation#5]
subDirectory運用をしている場合、サーバーアドレスに接続に行くと404となります。サブディレクトリを解除すると問題なく録画ファイルを確認できました。
念の為、サブディレクトリ運用時に、サーバーアドレス指定をサブディレクトリなしにしてみましたがやはりうまく接続できませんでした。
よろしくお願いします。

**Comment by l3tnun** [comment]
修正完了しました。
確認してみてください

**Comment by masahiko-imai** [comment]
確認できました。素早い対応有難うございました！！
