### ISSUE TITLE
Support Kodi 19 Matrix

### ISSUE THREAD

**Issue by uphy** [l3tnun/plugin.video.epgstation#9]
こちらのプラグインは、Python 2を実行環境として想定しているようですが、Kodi 19ではPython 2のサポートがなくなったようです。
https://github.com/l3tnun/plugin.video.epgstation/blob/635178adae4cfe8f7f5bf7e7b7f7b7a5fee0da5d/addon.xml#L7

Python 3へのmigrationが必要かもしれません。

**Comment by l3tnun** [comment]
手が空き次第対応しますが、優先度は低いです。

**Comment by l3tnun** [comment]
プルリクを受けまして v1, v2 共に kodi 19 にて動作するようになりましたので閉じます。
